config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('departments/', include('departments.urls')),
    path('employees/', include('employees.urls')),
    path('signin/', auth_views.LoginView.as_view(template_name="signin.html"), name="login"),
    path('', include("dashboard.urls")),
    path('accounts/', include('accounts.urls')),
]

departments/urls.py
from django.urls import path
from . import views

app_name = "departments"

urlpatterns = [
    path('read/', views.read),
    path('search/',views.search),
    path('search-list/', views.DepartmentsListView.as_view(), name ="department_list"),
    path('add/', views.DepartmentsCreateView.as_view(), name="department_add"),
    path('<str:dept_no>/edit',views.DepartmentsUpdateView.as_view(), name="department_update"),
    path('delete/<str:pk>', views.DepartmentsDeleteView.as_view(), name="department_delete"),
    path('fetch-live/', views.fetch_live),
    path('fetch-sleep/', views.fetch_sleep),
]

departments/models.py
from django.db import models

# Create your models here.

class Departments(models.Model) :
    dept_no = models.CharField(max_length=5, primary_key=True)
    dept_name = models.CharField(max_length=40)
    
    class Meta:
        managed = False
        db_table = 'departments'

departments/views.py
from django.shortcuts import render
from django.http import JsonResponse
from departments.models import Departments
from django.forms.models import model_to_dict
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .form import DepartmentForm 
import logging
import time

logger = logging.getLogger(__name__)

def fetch_live(request) :
    
    logger.info("fetch_live in")
    
    return JsonResponse({
        "fetch_live" : "ok"
    })
    
def fetch_sleep(request) :
    
    logger.info("fetch_sleep in")
    time.sleep(5)
    
    return JsonResponse({
        "fetch_sleep " : "wait"
    })
    
# Create your views here.
def read(request) :
    # TODO : 비즈니스 로직 호출
    return JsonResponse({
        "message" : "read called"    
    })
    

def search(request) :
    # TODO : 데이터베이스 조회
    dept_no = request.GET.get("dept_no")
    dept_name = request.GET.get("dept_name")
    
    # 아무것도 없을때
    qs = Departments.objects.all()
    
    # dept_no만 주어졌을때
    if dept_no:
        qs = qs.filter(dept_no=dept_no)
    
    # dept_name만 주어졌을때
    if dept_name:
        qs = qs.filter(dept_name=dept_name)
        
    # 두가지 방법 리스트 내포로 디셔너리로 바로 저장
    # model_to_dict 함수로 날것으로 저장이 아닌 바로 저장
    departments =[{"dept_no":departments.dept_no, "dept_name":department.dept_name} for department in qs]
    
    # list형태로 만들어서 사용
    data = list(qs.values("dept_no", "dept_name"))
    
    return JsonResponse(data, safe=False)

class DepartmentsListView(ListView) :
    
    model = Departments
    template_name = "departments/department_list.html"
    context_object_name = "departments"
    
    def get_queryset(self):
        
        queryset = super().get_queryset()
        dept_no = self.request.GET.get("dept_no")

        if dept_no :
            queryset = queryset.filter(dept_no=dept_no)

        queryset = queryset.order_by("dept_no")
        return queryset


class DepartmentsCreateView(CreateView) :
    model = Departments
    #fields = ["dept_no", "dept_name"]
    template_name = "departments/department_form.html"
    success_url = reverse_lazy("departments:department_list")
    form_class = DepartmentForm
    
    def form_valid(self, form):
        logger.info("form_valid")

        self.object = form.save()

        # fetch 요청인지 확인
        if self.request.headers.get("x-requested-with") == "fetch":
            return JsonResponse({
                "dept_no": self.object.dept_no,
                "dept_name": self.object.dept_name
            })

        return super().form_valid(form)

    def form_invalid(self, form):
        if self.request.headers.get("x-requested-with") == "fetch":
            return JsonResponse({
                "errors": form.errors
            }, status=400)

        return super().form_invalid(form)
    

class DepartmentsUpdateView(UpdateView) :
    model = Departments
    template_name = "departments/department_form.html"
    success_url = reverse_lazy("departments:department_list")
    form_class = DepartmentForm
    pk_url_kwarg = "dept_no"
    
class DepartmentsDeleteView(DeleteView) :
    model = Departments
    success_url = reverse_lazy("departments:department_list")
    

departments/templates/departments/department_form.html
{% extends 'base.html' %}
{% block title %}
부서추가
{% endblock title %}

{% block content %}

<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-xl-6">
            <div class="bg-secondary rounded h-100 p-4">
                <h6 class="mb-4">부서 추가</h6>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">저장</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
    

departments/templates/departments/department_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container-fluid pt-4 px-4">
        <div class="row g-4">
        <div class="col-sm-12 col-xl-12">
        <div class="bg-secondary rounded h-100 p-4">
        <button id="dept_modify" onclick="fetch_sleep()" type="submit" class="btn btn-primary w-30"> 비동기 재우기</button>
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#dept_add_modal"> 부서 추가  </button>
        <table class="table table-hover mb-0">
            <thead class="text-white border-bottom">
                <tr>
                    <th font-size= 30px>부서번호</th>
                    <th>부서이름</th>
                    <th>관리</th>
                    <th>비동기테스트</th>
                </tr>
            </thead>
            <tbody>
                {% for department in departments %}
                <tr>
                    <td><a href="{% url 'departments:department_update' department.dept_no %}">{{department.dept_no}}</a></td>
                    <td>{{department.dept_name}}</td>
                    <td>
                        <form method="post" action="{% url 'departments:department_delete' department.dept_no %}" onsubmit="return confirm('정말 삭제 하시겠습니까?');">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary w-30"> 삭제 </button>
                        </form>
                    </td>
                    <td>
                        <button id="dept_modify" onclick="fetch_live()" type="submit" class="btn btn-primary w-30"> 비동기 </button>
                    </td>
                    
                        
                    
                </tr>
                {% empty %}
                <tr>
                    <td colspan="2">조회 결과가 없습니다</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    </div>
</div>
</div>
<!-- Bootstrap Modal -->
<div class="modal fade" id="dept_add_modal" tabindex="-1" aria-hidden="true">
<div class="modal-dialog">
    <div class="modal-content bg-secondary rounded h-100 p-4">

    <div class="modal-header">
        <h5 class="modal-title">부서 추가</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="닫기"></button>
    </div>

    <div class="modal-body">
        <!-- CreateView로 보내는 form -->
        <form id="dept_add_form" action="{% url 'departments:department_add' %}" method="post">
        {% csrf_token %}
        <div class="mb-2">
            <label class="form-label">부서id</label>
            <input type="text" class="form-control col-sm-2 col-form-label" name="dept_no" id="modal_dept_no" placeholder="예) d100">
        </div>
        <div class="mb-2">
            <label class="form-label">부서명</label>
            <input type="text" class="form-control col-sm-2 col-form-label" name="dept_name" id="modal_dept_name" placeholder="예) 개발팀">
        </div>
        <div class="mb-2">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">취소</button>
            <button type="submit" class="btn btn-primary" id="dept_save">추가</button>
        </div>
        </form>
    </div>


    </div>
</div>
</div>
{% endblock content %}

{% block script %}
<script src="{% static 'js/departments.js' %}"></script>
{% endblock %}